/**
 * jobs.* handler — process-level scheduler API. Lives alongside the
 * other handlers/ entries but is registered last in methods.ts so its
 * `jobs` field on ServerRpcSurface is always populated by the time a
 * client can call it (initialize handshake gates non-init RPCs).
 *
 * The method names live in `scheduler/jobsRpc.ts` rather than
 * `@taco-ai/shared` so PR4 doesn't widen the shared package; the UI
 * mirrors them in `clients/taco-desktop/src/lib/jobsRpc.ts`. Drift
 * would surface as an unknown-method error at the first request.
 *
 * Every method carries a `Type.Any()` placeholder schema — the
 * `schemaValidation` test enforces coverage and rejects methods
 * without one. Real validation is deferred; the handlers' own
 * `expectString` / `assertJob` checks surface `invalid_params` for
 * malformed input today.
 */

import { Type } from "typebox";
import { JobsScopeError } from "../../lib/jobsErrors.ts";
import { safeJobId } from "../../scheduler/jobId.ts";
import { JOBS_RPC } from "../../scheduler/jobsRpc.ts";
import type { Actor, Job, SessionStrategy } from "../../scheduler/types.ts";
import { type MethodCtx, RpcHandlerError, registerMethod } from "../methodRegistry.ts";

// Reserved for future use; today the list endpoint takes no params.
type EmptyParams = Record<string, never>;

interface JobsListResult {
    jobs: Job[];
}

interface JobsGetParams {
    id: string;
    actor?: Actor;
}
interface JobsGetResult {
    job: Job | null;
}

interface JobsCreateParams {
    job: Job;
    actor?: Actor;
}
interface JobsCreateResult {
    job: Job;
}

interface JobsUpdateParams {
    job: Job;
    actor?: Actor;
}
interface JobsUpdateResult {
    job: Job;
}

interface JobsDeleteParams {
    id: string;
    actor?: Actor;
}
interface JobsDeleteResult {
    deleted: boolean;
}

interface JobsRunNowParams {
    id: string;
    actor?: Actor;
}
interface JobsRunNowResult {
    ran: boolean;
}

interface JobsHistoryParams {
    id: string;
    actor?: Actor;
}
interface JobsHistoryResult {
    history: Job["history"] | null;
}

/** Extract an optional `Actor` from params; returns undefined when absent
 *  or malformed (legacy callers / admin tooling). The presence of a
 *  well-formed actor is what gates scope enforcement in JobsController. */
function extractActor(params: unknown): Actor | undefined {
    if (typeof params !== "object" || params === null) return undefined;
    const raw = (params as Record<string, unknown>).actor;
    if (typeof raw !== "object" || raw === null) return undefined;
    const obj = raw as Record<string, unknown>;
    if (obj.kind === "im") {
        if (
            typeof obj.channelId === "string" &&
            typeof obj.peerId === "string" &&
            typeof obj.chatId === "string"
        ) {
            return { kind: "im", channelId: obj.channelId, peerId: obj.peerId, chatId: obj.chatId };
        }
        return undefined;
    }
    if (obj.kind === "ide" && typeof obj.workspace === "string") {
        return { kind: "ide", workspace: obj.workspace };
    }
    return undefined;
}

export function registerJobsHandlers(): void {
    registerMethod(
        JOBS_RPC.list,
        false,
        async ({ server, params }: MethodCtx<EmptyParams>): Promise<JobsListResult> => {
            const actor = extractActor(params);
            const jobs = server.jobs ? await server.jobs.list(actor) : [];
            return { jobs };
        },
        { schema: Type.Any() },
    );

    registerMethod(
        JOBS_RPC.get,
        false,
        async ({ server, params }: MethodCtx<JobsGetParams>): Promise<JobsGetResult> => {
            const id = expectString(params, "id");
            safeJobId(id);
            const actor = extractActor(params);
            const job = server.jobs ? await server.jobs.get(id, actor) : null;
            return { job };
        },
        { schema: Type.Any() },
    );

    registerMethod(
        JOBS_RPC.create,
        false,
        async ({ server, params }: MethodCtx<JobsCreateParams>): Promise<JobsCreateResult> => {
            if (!server.jobs) throw new RpcHandlerError("not_ready", "scheduler not running");
            const job = { ...assertJob(params, "job"), id: "" };
            // Create IDs are generated by the daemon. A supplied id is
            // ignored by JobsController rather than becoming an overwrite key.
            const actor = extractActor(params);
            try {
                const saved = await server.jobs.create(job, actor);
                return { job: saved };
            } catch (err) {
                throw scopeErrorToRpc(err);
            }
        },
        { schema: Type.Any() },
    );

    registerMethod(
        JOBS_RPC.update,
        false,
        async ({ server, params }: MethodCtx<JobsUpdateParams>): Promise<JobsUpdateResult> => {
            if (!server.jobs) throw new RpcHandlerError("not_ready", "scheduler not running");
            const job = assertJob(params, "job", true);
            safeJobId(job.id);
            const actor = extractActor(params);
            try {
                const saved = await server.jobs.update(job, actor);
                return { job: saved };
            } catch (err) {
                throw scopeErrorToRpc(err);
            }
        },
        { schema: Type.Any() },
    );

    registerMethod(
        JOBS_RPC.delete,
        false,
        async ({ server, params }: MethodCtx<JobsDeleteParams>): Promise<JobsDeleteResult> => {
            if (!server.jobs) throw new RpcHandlerError("not_ready", "scheduler not running");
            const id = expectString(params, "id");
            safeJobId(id);
            const actor = extractActor(params);
            let existed = false;
            try {
                existed = (await server.jobs.get(id, actor)) !== null;
                await server.jobs.delete(id, actor);
            } catch (err) {
                throw scopeErrorToRpc(err);
            }
            return { deleted: existed };
        },
        { schema: Type.Any() },
    );

    registerMethod(
        JOBS_RPC.runNow,
        false,
        async ({ server, params }: MethodCtx<JobsRunNowParams>): Promise<JobsRunNowResult> => {
            if (!server.jobs) throw new RpcHandlerError("not_ready", "scheduler not running");
            const id = expectString(params, "id");
            safeJobId(id);
            const actor = extractActor(params);
            let ran = false;
            try {
                ran = await server.jobs.runNow(id, actor);
            } catch (err) {
                throw scopeErrorToRpc(err);
            }
            return { ran };
        },
        { schema: Type.Any() },
    );

    registerMethod(
        JOBS_RPC.history,
        false,
        async ({ server, params }: MethodCtx<JobsHistoryParams>): Promise<JobsHistoryResult> => {
            const id = expectString(params, "id");
            safeJobId(id);
            const actor = extractActor(params);
            const history = server.jobs ? await server.jobs.history(id, actor) : null;
            return { history };
        },
        { schema: Type.Any() },
    );
}

// Suppress unused warning — EmptyParams documents the intent that
// list() takes no params today; the type alias keeps the schema's `Type.Any()`
// shape honest when we eventually tighten it.
void (null as unknown as EmptyParams);

function expectString(params: unknown, field: string): string {
    if (typeof params !== "object" || params === null) {
        throw new RpcHandlerError(
            "invalid_params",
            `params must be an object (got ${typeof params})`,
        );
    }
    const value = (params as Record<string, unknown>)[field];
    if (typeof value !== "string" || value.length === 0) {
        throw new RpcHandlerError("invalid_params", `${field} must be a non-empty string`);
    }
    return value;
}

function assertJob(params: unknown, field: string, requireId = false): Job {
    if (typeof params !== "object" || params === null) {
        throw new RpcHandlerError(
            "invalid_params",
            `params must be an object (got ${typeof params})`,
        );
    }
    const candidate = (params as Record<string, unknown>)[field];
    if (typeof candidate !== "object" || candidate === null) {
        throw new RpcHandlerError("invalid_params", `${field} must be a job object`);
    }
    const obj = candidate as Record<string, unknown>;
    if (requireId && (typeof obj.id !== "string" || obj.id.length === 0)) {
        throw new RpcHandlerError("invalid_params", `${field}.id must be a non-empty string`);
    }
    if (typeof obj.name !== "string") {
        throw new RpcHandlerError("invalid_params", `${field}.name must be a string`);
    }
    if (!isScheduleSpec(obj.schedule)) {
        throw new RpcHandlerError("invalid_params", `${field}.schedule is malformed`);
    }
    if (typeof obj.command !== "string") {
        throw new RpcHandlerError("invalid_params", `${field}.command must be a string`);
    }
    // The scheduler dispatcher only knows `agent.invoke` today — every other
    // command would land in `dispatcher.createJobDispatcher` and throw
    // `unsupported scheduled command`. Refuse here so the failure is
    // actionable (a clear invalid_params) instead of a recurring err entry
    // in the job's history. When a real second command shows up, add it to
    // the set AND wire the dispatcher to handle it.
    if (obj.command !== "agent.invoke") {
        throw new RpcHandlerError(
            "invalid_params",
            `${field}.command must be "agent.invoke" ` +
                "(scheduler dispatches to a fresh agent session; " +
                "place shell-style commands in args.prompt and let the agent " +
                `route them through tools). Got: ${JSON.stringify(obj.command)}`,
        );
    }
    if (typeof obj.args !== "object" || obj.args === null) {
        throw new RpcHandlerError("invalid_params", `${field}.args must be an object`);
    }
    const argsObj = obj.args as Record<string, unknown>;
    if (typeof argsObj.workspace !== "string" || argsObj.workspace.length === 0) {
        throw new RpcHandlerError(
            "invalid_params",
            `${field}.args.workspace is required and must be a non-empty string`,
        );
    }
    // `agent.invoke` requires a prompt. Same allowlist argument: every other
    // shape falls through to a no-context agent session that has nothing to
    // do, and the operator only notices via silent history entries.
    if (typeof argsObj.prompt !== "string" || argsObj.prompt.length === 0) {
        throw new RpcHandlerError(
            "invalid_params",
            `${field}.args.prompt is required and must be a non-empty string`,
        );
    }
    if (typeof obj.enabled !== "boolean") {
        throw new RpcHandlerError("invalid_params", `${field}.enabled must be a boolean`);
    }
    if (typeof obj.run_on_startup !== "boolean") {
        throw new RpcHandlerError("invalid_params", `${field}.run_on_startup must be a boolean`);
    }
    if (obj.sessionStrategy !== undefined && !isSessionStrategy(obj.sessionStrategy)) {
        throw new RpcHandlerError(
            "invalid_params",
            `${field}.sessionStrategy must be "new" | "reuse" | "pin"`,
        );
    }
    return { ...obj, id: typeof obj.id === "string" ? obj.id : "" } as unknown as Job;
}

function isScheduleSpec(value: unknown): boolean {
    if (typeof value !== "object" || value === null) return false;
    const s = value as Record<string, unknown>;
    if (s.kind === "cron") {
        return (
            typeof s.expr === "string" &&
            s.expr.length > 0 &&
            (s.tz === undefined || typeof s.tz === "string")
        );
    }
    if (s.kind === "interval") {
        return typeof s.ms === "number" && Number.isInteger(s.ms) && s.ms > 0;
    }
    return false;
}

function isSessionStrategy(value: unknown): value is SessionStrategy {
    return value === "new" || value === "reuse" || value === "pin";
}

/** Map JobsController's scope errors to wire codes. Out-of-scope reads
 *  are mapped to `not_found` (never leak existence); writes are
 *  `forbidden` so the caller can distinguish "missing" from "denied". */
function scopeErrorToRpc(err: unknown): RpcHandlerError {
    if (err instanceof JobsScopeError) {
        return new RpcHandlerError(err.code, err.message);
    }
    // Re-throw unknown errors so the existing try/catch chain (or the
    // handler wrapper) maps them to internal_error.
    throw err;
}
