/** macOS service registration. launchd executes a self-contained wrapper
 *  because its plist environment is static; paths are shell-quoted in the
 *  wrapper and XML-escaped only in the plist. */

import { writeFileSync } from "node:fs";
import { connect } from "node:net";
import { homedir } from "node:os";
import { join } from "node:path";
import type { InstallResult } from "./install.ts";
import { execFile, type PlatformPkgPaths } from "./installHelpers.ts";

/** launchd label — appears in `launchctl list` + the LaunchAgents filename. */
export const LAUNCHD_LABEL = "com.taco-ai.sidecar";

/** LaunchAgent plist path under $HOME. */
export function launchdPlistPath(): string {
    return join(homedir(), "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

/** POSIX wrapper script name under $TACO_HOME/bin/. */
export function posixWrapperPath(tacoHome: string): string {
    return join(tacoHome, "bin", "taco-sidecar-daemon");
}

/** Escape XML special characters in attribute / element values. */
export function escapeXml(value: string): string {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&apos;");
}

export interface PosixWrapperOptions {
    socketPath: string;
    controlSocketPath: string;
    nodeBin: string;
    bundle: string;
    resourcesRoot: string;
}

function quoteShell(value: string): string {
    return `'${value.replace(/'/g, "'\\''")}'`;
}

export function renderPosixWrapper(opts: PosixWrapperOptions): string {
    return `#!/bin/sh
# Generated by 'taco install' — do not edit.
set -e

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TACO_HOME=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
export TACO_HOME

export TACO_SOCKET=${quoteShell(opts.socketPath)}
export TACO_CONTROL_SOCKET=${quoteShell(opts.controlSocketPath)}
export TACO_DAEMON_MODE=1
export TACO_SIDECAR_RESOURCES=${quoteShell(opts.resourcesRoot)}

NODE_BIN=${quoteShell(opts.nodeBin)}
BUNDLE=${quoteShell(opts.bundle)}
exec "$NODE_BIN" "$BUNDLE"
`;
}

export interface LaunchdPlistOptions {
    wrapperPath: string;
    tacoHome: string;
    logDir: string;
}

/** Generate the launchd plist XML. KeepAlive covers crash + abnormal exit;
 *  ThrottleInterval prevents a tight crash loop from eating CPU. */
export function renderLaunchdPlist(opts: LaunchdPlistOptions): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>          <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(opts.wrapperPath)}</string>
  </array>
  <key>RunAtLoad</key>      <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key> <false/>
    <key>Crashed</key>        <true/>
  </dict>
  <key>ProcessType</key>    <string>Background</string>
  <key>Nice</key>           <integer>5</integer>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key> <string>${escapeXml(opts.logDir)}/daemon.out.log</string>
  <key>StandardErrorPath</key><string>${escapeXml(opts.logDir)}/daemon.err.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>TACO_HOME</key>     <string>${escapeXml(opts.tacoHome)}</string>
  </dict>
</dict>
</plist>
`;
}

export interface InstallLaunchdInput {
    tacoHome: string;
    pkg: PlatformPkgPaths;
    socket: string;
    control: string;
    logDir: string;
}

/** Probe the NDJSON socket until a connect attempt succeeds or the deadline
 *  expires. Mirrors the CLI's waitForSocket (start.ts) so launchd and the
 *  desktop agree on the "ready" heuristic. */
export function waitForSocket(path: string, timeoutMs: number): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    return new Promise((resolve, reject) => {
        const attempt = () => {
            const sock = connect(path);
            const finish = (err?: Error) => {
                sock.removeAllListeners();
                sock.destroy();
                if (err) reject(err);
                else resolve();
            };
            sock.once("connect", () => finish());
            sock.once("error", (e) => {
                if (Date.now() >= deadline) {
                    finish(new Error(`socket ${path} not ready in ${timeoutMs}ms (${e.message})`));
                } else {
                    setTimeout(attempt, 100);
                }
            });
        };
        attempt();
    });
}

/** Run the macOS install: write wrapper + plist, `launchctl load -w`,
 *  then wait for the daemon socket to appear. Throws if the load fails or
 *  the daemon doesn't come up within 10s. */
export async function installLaunchd(input: InstallLaunchdInput): Promise<InstallResult> {
    const wrapperPath = posixWrapperPath(input.tacoHome);
    const plistPath = launchdPlistPath();

    const wrapperContent = renderPosixWrapper({
        socketPath: input.socket,
        controlSocketPath: input.control,
        nodeBin: input.pkg.nodeBin,
        bundle: input.pkg.bundle,
        resourcesRoot: input.pkg.resources,
    });
    writeFileSync(wrapperPath, wrapperContent, { mode: 0o755 });

    const plistContent = renderLaunchdPlist({
        wrapperPath,
        tacoHome: input.tacoHome,
        logDir: input.logDir,
    });
    writeFileSync(plistPath, plistContent, { mode: 0o644 });

    // `-w` persists the load across reboots; without it launchd forgets the
    // agent on the next login and the desktop has to re-install.
    await execFile("launchctl", ["load", "-w", plistPath]);

    try {
        await waitForSocket(input.socket, 10_000);
    } catch (err) {
        throw new Error(
            `launchctl load succeeded but daemon socket ${input.socket} did not appear: ${err}`,
        );
    }

    return {
        serviceManager: "launchd",
        wrapperPath,
        plistPath,
    };
}
