/** Windows service registration through Task Scheduler. `ONSTART` matches
 *  the boot-time daemon contract; the wrapper bakes in the per-user home and
 *  runtime paths because schtasks cannot define environment variables. */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { InstallResult } from "./install.ts";
import { execFile, type PlatformPkgPaths } from "./installHelpers.ts";

/** Scheduled task name — appears in `schtasks /Query /TN` + the wrapper. */
export const SCHTASKS_NAME = "TacoSidecar";

/** Windows wrapper script name under $TACO_HOME\bin\. */
export function windowsWrapperPath(tacoHome: string): string {
    return join(tacoHome, "bin", "taco-sidecar-daemon.cmd");
}

/** Escape characters that cmd treats as syntax (`& | < > ^ " %`) when they
 *  appear inside a `set VAR=value` line. Delimiters like `%` and `!` are
 *  also escaped for safety (delayed expansion + for-variable substitution
 *  can otherwise leak through to the sidecar). */
export function escapeCmd(value: string): string {
    return value.replace(/[&|<>^"%!]/g, "^$&");
}

export interface WindowsWrapperOptions {
    tacoHome: string;
    socketPath: string;
    controlSocketPath: string;
    nodeBin: string;
    bundle: string;
    resourcesRoot: string;
}

/** Generate the Windows .cmd wrapper content. Every value is baked in so
 *  schtasks can invoke the .cmd with no args — schtasks /TR passes the
 *  script path verbatim. The wrapper resolves TACO_HOME at runtime (with
 *  the install-time value as fallback) so re-running `taco install` from
 *  a different user still lands the daemon under the right home. */
export function renderWindowsWrapper(opts: WindowsWrapperOptions): string {
    const tacoHome = escapeCmd(opts.tacoHome);
    const socket = escapeCmd(opts.socketPath);
    const control = escapeCmd(opts.controlSocketPath);
    const nodeBin = escapeCmd(opts.nodeBin);
    const bundle = escapeCmd(opts.bundle);
    const resourcesRoot = escapeCmd(opts.resourcesRoot);
    return `@echo off
rem Generated by 'taco install' — do not edit.
rem Invokes the bundled sidecar in daemon mode under schtasks.
setlocal EnableExtensions EnableDelayedExpansion

rem Scheduled tasks do not inherit the installer's environment, so bake the
rem per-user TACO_HOME into the wrapper.
set "TACO_HOME=${tacoHome}"

rem Socket paths (must match packages/cli/lib/paths.ts on Windows).
set "TACO_SOCKET=${socket}"
set "TACO_CONTROL_SOCKET=${control}"

rem Daemon-mode env the sidecar bundle reads on startup.
set "TACO_DAEMON_MODE=1"
set "TACO_SIDECAR_RESOURCES=${resourcesRoot}"

rem Bundled node + sidecar entry (resolved at install time).
set "NODE_BIN=${nodeBin}"
set "BUNDLE=${bundle}"

"!NODE_BIN!" "!BUNDLE!"
endlocal
`;
}

export interface InstallSchtasksInput {
    tacoHome: string;
    pkg: PlatformPkgPaths;
    socket: string;
    control: string;
}

/** Run the Windows install: write the .cmd wrapper + create the scheduled
 *  task via schtasks. We don't wait for the daemon socket (Windows named
 *  pipes don't have a stable readiness signal without a probe round-trip
 *  matching the sidecar's hello frame); the desktop's `resolve_sidecar`
 *  handles reconnect + retry. */
export async function installSchtasks(input: InstallSchtasksInput): Promise<InstallResult> {
    const wrapperPath = windowsWrapperPath(input.tacoHome);

    const wrapperContent = renderWindowsWrapper({
        tacoHome: input.tacoHome,
        socketPath: input.socket,
        controlSocketPath: input.control,
        nodeBin: input.pkg.nodeBin,
        bundle: input.pkg.bundle,
        resourcesRoot: input.pkg.resources,
    });
    writeFileSync(wrapperPath, wrapperContent, { mode: 0o755 });

    // `/SC ONLOGON` so the daemon runs in the user's context — $TACO_HOME
    // under %USERPROFILE%\.taco is a per-user path. `/RL HIGHEST` runs the
    // task with the highest privileges available (still the user). `/F`
    // overwrites any prior registration; re-running `taco install` is the
    // supported update path.
    await execFile("schtasks", [
        "/Create",
        "/SC",
        "ONSTART",
        "/TN",
        SCHTASKS_NAME,
        "/TR",
        `"${wrapperPath}"`,
        "/RL",
        "HIGHEST",
        "/F",
    ]);

    // Kick the task immediately so the user doesn't have to sign out + in
    // to see the install take effect. `/Run` returns once the task is
    // dispatched, not when the daemon is ready — the desktop handles
    // reconnect.
    await execFile("schtasks", ["/Run", "/TN", SCHTASKS_NAME], { allowFailure: true });

    return {
        serviceManager: "schtasks",
        wrapperPath,
        taskName: SCHTASKS_NAME,
    };
}
