/** Windows service registration through Task Scheduler. The daemon is
 *  per-user ($TACO_HOME lives under %USERPROFILE%), so the task runs as the
 *  creating user at logon — ONLOGON without /RU — never elevated, so the
 *  installer can terminate the process when upgrading over a live daemon.
 *  The wrapper bakes in the per-user home and runtime paths because schtasks
 *  cannot define environment variables.
 *
 *  The scheduled-task action is `wscript.exe //nologo <wrapper.vbs>`, not a
 *  `.cmd`. A `.cmd` is launched through `cmd.exe` (console subsystem), which
 *  flashes a console at logon; `wscript.exe` is a GUI-subsystem host, and
 *  the VBS starts node with `Run(..., 0, True)` (SW_HIDE + wait) so neither
 *  wscript nor the console-subsystem node binary pops a window. Wait=True
 *  keeps the task "Running" for the daemon's lifetime so `schtasks /End`
 *  still tears the tree down. macOS launchd is a separate file and is not
 *  involved here. */

import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { InstallResult } from "./install.ts";
import { execFile, type PlatformPkgPaths } from "./installHelpers.ts";

/** Scheduled task name — appears in `schtasks /Query /TN` + the wrapper. */
export const SCHTASKS_NAME = "TacoSidecar";

/** Windows wrapper script name under $TACO_HOME\bin\. */
export function windowsWrapperPath(tacoHome: string): string {
    return join(tacoHome, "bin", "taco-sidecar-daemon.vbs");
}

/** Pre-vbs wrapper left behind by older installs. Inert once the task
 *  points at the .vbs; removed on re-install so operators don't keep two
 *  launchers around. */
export function legacyWindowsCmdPath(tacoHome: string): string {
    return join(tacoHome, "bin", "taco-sidecar-daemon.cmd");
}

/** Escape a string for embedding inside a VBScript `"..."` literal.
 *  The only metacharacter VBS strings have is `"` itself (doubled). `&`
 *  is concatenation only outside quotes, so paths like `C:\R&D` pass
 *  through unchanged — unlike the old `.cmd` `set` lines. */
export function escapeVbs(value: string): string {
    return value.replace(/"/g, '""');
}

export interface WindowsWrapperOptions {
    tacoHome: string;
    socketPath: string;
    controlSocketPath: string;
    nodeBin: string;
    bundle: string;
    resourcesRoot: string;
}

/** Generate the Windows .vbs wrapper content. Every value is baked in so
 *  schtasks can invoke wscript with no extra args. The wrapper sets
 *  process-level env (inherited by node) because Task Scheduler has no
 *  env-var field, then `Run`s the bundled node hidden and waits. */
export function renderWindowsWrapper(opts: WindowsWrapperOptions): string {
    const tacoHome = escapeVbs(opts.tacoHome);
    const socket = escapeVbs(opts.socketPath);
    const control = escapeVbs(opts.controlSocketPath);
    const nodeBin = escapeVbs(opts.nodeBin);
    const bundle = escapeVbs(opts.bundle);
    const resourcesRoot = escapeVbs(opts.resourcesRoot);
    // Backslash join, not `path.join`: this renderer is unit-tested on
    // POSIX CI too, and `path.join` would emit `/logs/` there.
    const stderrLog = escapeVbs(`${opts.tacoHome}\\logs\\daemon.err.log`);
    return `' Generated by 'taco install' — do not edit.
' Invokes the bundled sidecar in daemon mode under schtasks.
' Window style 0 (SW_HIDE) + wait so logon does not flash a console.
Option Explicit
Dim sh, env
Set sh = CreateObject("WScript.Shell")
Set env = sh.Environment("Process")

' Scheduled tasks do not inherit the installer's environment, so bake the
' per-user TACO_HOME into the wrapper.
env("TACO_HOME") = "${tacoHome}"

' Socket paths (must match packages/cli/lib/paths.ts on Windows).
env("TACO_SOCKET") = "${socket}"
env("TACO_CONTROL_SOCKET") = "${control}"

' Daemon-mode env the sidecar bundle reads on startup.
env("TACO_DAEMON_MODE") = "1"
env("TACO_SIDECAR_RESOURCES") = "${resourcesRoot}"

' No console to inherit, so tee sidecar stderr to the same file launchd
' gets via StandardErrorPath.
env("TACO_STDERR_LOG") = "${stderrLog}"

WScript.Quit sh.Run("""${nodeBin}"" ""${bundle}""", 0, True)
`;
}

export interface InstallSchtasksInput {
    tacoHome: string;
    pkg: PlatformPkgPaths;
    socket: string;
    control: string;
}

/** Args for the `schtasks /Create` call. Pure so tests can pin the contract
 *  that keeps the daemon killable by the installer:
 *  - ONLOGON without /RU runs the task as the creating user at sign-in.
 *    (ONSTART without /RU would run as SYSTEM, whose processes a per-user
 *    installer cannot kill — the source of "Error opening file for writing"
 *    on upgrade.)
 *  - No /RL HIGHEST: the daemon is pure user-mode; elevation only breaks
 *    the installer's ability to terminate it.
 *  - /F overwrites any prior registration; re-running `taco install` is the
 *    supported update path.
 *  - /TR is `wscript.exe //nologo "<wrapper.vbs>"` rather than the .vbs
 *    path alone, so Task Scheduler never resolves the action through
 *    `cmd.exe` / the `.vbs` file association (either of which can flash
 *    a console). The wrapper path is quoted so usernames with spaces work. */
export function schtasksCreateArgs(wrapperPath: string): string[] {
    return [
        "/Create",
        "/SC",
        "ONLOGON",
        "/TN",
        SCHTASKS_NAME,
        "/TR",
        `wscript.exe //nologo "${wrapperPath}"`,
        "/F",
    ];
}

/** Run the Windows install: write the .vbs wrapper + create the scheduled
 *  task via schtasks. We don't wait for the daemon socket (Windows named
 *  pipes don't have a stable readiness signal without a probe round-trip
 *  matching the sidecar's hello frame); the desktop's `resolve_sidecar`
 *  handles reconnect + retry. */
export async function installSchtasks(input: InstallSchtasksInput): Promise<InstallResult> {
    const wrapperPath = windowsWrapperPath(input.tacoHome);

    const wrapperContent = renderWindowsWrapper({
        tacoHome: input.tacoHome,
        socketPath: input.socket,
        controlSocketPath: input.control,
        nodeBin: input.pkg.nodeBin,
        bundle: input.pkg.bundle,
        resourcesRoot: input.pkg.resources,
    });
    // UTF-16 LE + BOM: wscript reads .vbs as the system ANSI code page
    // unless the file is Unicode, and TACO_HOME for a non-ASCII username
    // would otherwise be garbled.
    writeFileSync(wrapperPath, `\uFEFF${wrapperContent}`, { encoding: "utf16le" });

    await execFile("schtasks", schtasksCreateArgs(wrapperPath));

    // Drop the pre-vbs .cmd only after /Create succeeds. Doing it first
    // would leave a failed install pointing at a missing launcher (the
    // old ONLOGON task still targets taco-sidecar-daemon.cmd). Once the
    // task is retargeted at the .vbs the leftover is inert.
    const legacyCmd = legacyWindowsCmdPath(input.tacoHome);
    try {
        if (existsSync(legacyCmd)) unlinkSync(legacyCmd);
    } catch {
        // Best-effort: the .cmd is unused once the task points at the .vbs.
    }

    // Kick the task immediately so the user doesn't have to sign out + in
    // to see the install take effect. `/Run` returns once the task is
    // dispatched, not when the daemon is ready — the desktop handles
    // reconnect.
    await execFile("schtasks", ["/Run", "/TN", SCHTASKS_NAME], { allowFailure: true });

    return {
        serviceManager: "schtasks",
        wrapperPath,
        taskName: SCHTASKS_NAME,
    };
}
